language: python
python:
  - "3.9"

before_install:
  - python -m pip install --upgrade pip

install:
  # Step 1 : Install virtual environment
  - virtualenv -p python3 venv

services:
  - postgresql

env:
  global:
    - PGPORT=5432

before_script:
  - wget https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_mac64.zip
  - unzip chromedriver_mac64.zip -d ~
#  - unzip chromedriver_mac64.zip -d ~/home/travis/virtualenv/python3.9/bin/
  - export CHROME_BIN=chromium-browser

script:
  # Step 2 : Activate the virtual environment
  - source venv/bin/activate

  # Step 3 : Install libraries
  - pip install -r requirements.txt
  - pip install six
  - pip install webdriver-manager
  - export ENV='production'
  - sudo -u postgres psql -c 'create user nsengmany;'
  - sudo -u postgres psql -c 'create database django_project_bdd;'
  - sudo -u postgres psql -c 'ALTER ROLE nsengmany SET client_encoding TO "utf8";'
  - sudo -u postgres psql -c 'ALTER ROLE nsengmany SET default_transaction_isolation TO "read committed";'
  - sudo -u postgres psql -c 'ALTER ROLE nsengmany SET timezone TO "Europe/Paris";'
  - sudo -u postgres psql -c 'ALTER ROLE nsengmany WITH SUPERUSER;'

  - sudo -u postgres psql -c 'GRANT ALL PRIVILEGES ON DATABASE django_project_bdd TO nsengmany;'
  - sudo -u postgres psql -c 'GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nsengmany;'

  - sudo -u postgres psql -c '\l'
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py insert_data
  - python manage.py insert_products
  - python manage.py collectstatic --noinput

#  - pwd
#  - cd purbeurre_website/tests/functional_tests
#  - export pythonpath="$(/home/travis/build/nicoseng/P10_purbeurre/purbeurre_website/tests/functional_tests/)"
#  - chmod +x manage.py
#  - wget https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_mac64.zip
#  - unzip chromedriver_mac64.zip -d ~/
#  - export CHROME_BIN=chromium-browser
#  - self.browser = webdriver.Chrome(service=service)
#  - self.browser.maximize_window()


  # Step 5 : Testing the application
  - pytest