language: python
python:
  - "3.6"

before_install:
  - python -m pip install --upgrade pip


install:
  # Step 1 : Install virtual environment
  - virtualenv -p python3 venv

services:
  - postgresql

addons:
  postgresql: 13
  apt:
    packages:
      - postgresql-13
env:
  global:
    - PGPORT=5433



script:
  # Step 1 : Activate the virtual environment
  - source venv/bin/activate
  - pip install -r requirements.txt

  # Step 2 : Install postgresql
  - sudo apt-get update
  - sudo apt-get install python3-pip python3-dev libpq-dev postgresql postgresql-contrib
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf

  # Step 3 : Retrieve the project
  - git clone https://github.com/nicoseng/P10_purbeurre.git

  # Step 4 : Open the database
  - sudo pg_ctlcluster 13 main start
  - sudo systemctl status postgresql@13-main.service

  # Step 5 : Create the database
  - cd ~postgres/
  - sudo -u postgres psql -c 'create database purbeurre_bdd;'
  - sudo -u postgres psql -c '\l'
#  - sudo -u postgres psql -c 'ALTER ROLE purbeurre_user SET client_encoding TO 'utf8';'
#  - sudo -u postgres psql -c 'ALTER ROLE purbeurre_user SET default_transaction_isolation TO 'read committed';'
#  - sudo -u postgres psql -c 'ALTER ROLE purbeurre_user SET timezone TO 'Europe/Paris;'
  - sudo -u postgres psql -c '\q'
  - ls -a

    #  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
#  - sudo -u postgres psql
#  - psql -c 'create database test_db;'
#  - psql -c 'create database test_db;' -U postgres
#  - CREATE DATABASE purbeurre_bdd;
#  - CREATE USER purbeurre_user WITH PASSWORD 'lunaires';
#  - ALTER ROLE purbeurre_user SET client_encoding TO 'utf8';
#  - ALTER ROLE purbeurre_user SET default_transaction_isolation TO 'read committed';
#  - ALTER ROLE purbeurre_user SET timezone TO 'Europe/Paris';
#  - GRANT ALL PRIVILEGES ON DATABASE purbeurre_bdd TO purbeurre_user;
#  - \l;
#  - \q
#  - export ENV=PRODUCTION
#  - manage.py collectstatic
  # Step 4 : Migrate datas in the database
#  - python manage.py makemigrations
#  - python manage.py migrate
#  - python manage.py insert_data
#  - python manage.py insert_products
#  # Step 5 : Testing the application
#  - pytest