language: python
python:
  - "3.6"

before_install:
  - python -m pip install --upgrade pip
  - pip3 install --upgrade pip

install:
  # Step 1 : Install virtual environment
#  - virtualenv -p python3 venv
#  - source venv/bin/activate

  # Step 2 : Install dependencies
  - pip install -r requirements.txt

script:
  - virtualenv -p python3 venv
  - source venv/bin/activate
  - pytest