language: python
python:
  - "3.9"

before_install:
  - python -m pip install --upgrade pip

install:
  # Step 1 : Install virtual environment
  - virtualenv -p python3 venv

services:
  - postgresql

env:
  global:
    - PGPORT=5433

script:
  # Step 2 : Activate the virtual environment
  - source venv/bin/activate

  # Step 3 : Install libraries
  - pip install -r requirements.txt
  - export ENV=production
  - sudo -u postgres psql -c 'create database purbeurre_db;'
  - sudo -u postgres psql -c '\l'
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py insert_data
  - python manage.py insert_products
#  - export ENV=production

  # Step 5 : Testing the application
  - pytest