language: python
python:
  - "3.9"

addons:
  chrome: stable

before_install:
  - python -m pip install --upgrade pip

install:
  # Step 1 : Install virtual environment
  - virtualenv -p python3 venv

services:
  - postgresql

env:
  global:
    - PGPORT=5432


script:
  # Step 2 : Activating the virtual environment
  - source venv/bin/activate

  # Step 3 : Installing libraries
  - pip install -r requirements.txt
  - pip install six

  # Step 4 : Installing database
  - export ENV='production'
  - sudo -u postgres psql -c 'create user nsengmany;'
  - sudo -u postgres psql -c 'create database django_project_bdd;'
  - sudo -u postgres psql -c 'ALTER ROLE nsengmany SET client_encoding TO "utf8";'
  - sudo -u postgres psql -c 'ALTER ROLE nsengmany SET default_transaction_isolation TO "read committed";'
  - sudo -u postgres psql -c 'ALTER ROLE nsengmany SET timezone TO "Europe/Paris";'
  - sudo -u postgres psql -c 'ALTER ROLE nsengmany WITH SUPERUSER;'

  - sudo -u postgres psql -c 'GRANT ALL PRIVILEGES ON DATABASE django_project_bdd TO nsengmany;'
  - sudo -u postgres psql -c 'GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nsengmany;'

  - sudo -u postgres psql -c '\l'

  # Step 5 : Filling the database
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py insert_data
  - python manage.py insert_products
  - python manage.py collectstatic --noinput

  # Step 6 : Getting Chromedriver
  - ls
  - wget https://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_mac64.zip
  - unzip chromedriver_mac64.zip -d /home/travis/build/nicoseng/P10_purbeurre/purbeurre_website/tests/functional_tests/
  - pwd
  - cd purbeurre_website/tests/functional_tests/
  - ls
  - file chromedriver
  - uname -a

#  - chmod u=rwx,g=rx,o=r chromedriver
#  - export CHROME_BIN=chromium-browser

  # Step 7 : Testing the application
  - pytest