language: python
python:
  - "3.9"

addons:
  # ajouter uniquement les navigateurs utilisés
  chrome: stable

before_install:
  - python -m pip install --upgrade pip

install:
  # Step 1 : Install virtual environment
  - virtualenv -p python3 venv

services:
  - postgresql

env:
  global:
    - PGPORT=5432


script:
  # Step 2 : Activate the virtual environment
  - source venv/bin/activate

  # Step 3 : Install libraries
  - pip install -r requirements.txt
  - pip install six
  - export ENV='production'
  - sudo -u postgres psql -c 'create user nsengmany;'
  - sudo -u postgres psql -c 'create database django_project_bdd;'
  - sudo -u postgres psql -c 'ALTER ROLE nsengmany SET client_encoding TO "utf8";'
  - sudo -u postgres psql -c 'ALTER ROLE nsengmany SET default_transaction_isolation TO "read committed";'
  - sudo -u postgres psql -c 'ALTER ROLE nsengmany SET timezone TO "Europe/Paris";'
  - sudo -u postgres psql -c 'ALTER ROLE nsengmany WITH SUPERUSER;'

  - sudo -u postgres psql -c 'GRANT ALL PRIVILEGES ON DATABASE django_project_bdd TO nsengmany;'
  - sudo -u postgres psql -c 'GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nsengmany;'

  - sudo -u postgres psql -c '\l'
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py insert_data
  - python manage.py insert_products
  - python manage.py collectstatic --noinput

  - ls
  - wget https://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_mac_arm64.zip
  - unzip chromedriver_mac_arm64.zip -d /home/travis/build/nicoseng/P10_purbeurre/purbeurre_website/tests/functional_tests/
  - pwd
  - cd purbeurre_website/tests/functional_tests/
  - ls
  - chmod u=rwx,g=rx,o=r chromedriver
  - export CHROME_BIN=chromium-browser

  # Step 5 : Testing the application
  - pytest