language: python
python:
  - "3.6"

before_install:
  - python -m pip install --upgrade pip
  - cd purbeurre
#  - pip3 install --upgrade pip

install:
  # Step 1 : Install virtual environment
  - virtualenv -p python3 venv
  - source venv/bin/activate
  - pip install -r requirements.txt

  # Step 2 : Create the database
  - sudo apt-get update
  - sudo apt-get install python3-pip python3-dev libpq-dev postgresql postgresql-contrib
  - git clone https://github.com/nicoseng/P10_purbeurre.git

script:
  - python
  - exit()
#  - pytest
#  - sudo apt install virtualenv
#  - virtualenv -p python3 venv
#  - source venv/bin/activate
#  - pip install -r requirements.txt
#    # Step 3 : Create the database
#  - sudo -u postgres psql
#  -
#  - CREATE DATABASE purbeurre_bdd;
#  - CREATE USER purbeurre_user WITH PASSWORD 'lunaires';
#  - ALTER ROLE purbeurre_user SET client_encoding TO 'utf8';
#  - ALTER ROLE purbeurre_user SET default_transaction_isolation TO 'read committed';
#  - ALTER ROLE purbeurre_user SET timezone TO 'Europe/Paris';
#  - GRANT ALL PRIVILEGES ON DATABASE purbeurre_bdd TO purbeurre_user;
#  - \q
#  - export ENV=PRODUCTION
#  - manage.py collectstatic
    # Step 4 : Migrate datas in the database
#  - python manage.py makemigrations
#  - python manage.py migrate
#  - python manage.py insert_data
#  - python manage.py insert_products
  # Step 5 : Testing the application
#  - pytest