language: python
python:
  - "3.6"
  - "3.7"

before_install:
  - python -m pip install --upgrade pip

# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - pytest